# Generated by Django 5.2.5 on 2025-08-31 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('capacidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cepa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cepas', to='animales.especie')),
            ],
            options={
                'ordering': ['especie__nombre', 'nombre'],
                'unique_together': {('especie', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='GrupoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_machos', models.PositiveIntegerField(default=0)),
                ('cantidad_hembras', models.PositiveIntegerField(default=0)),
                ('stock_minimo_machos', models.PositiveIntegerField(default=0)),
                ('stock_minimo_hembras', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cepa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animales.cepa')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animales.especie')),
                ('jaula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animales.jaula')),
            ],
            options={
                'ordering': ['especie__nombre', 'cepa__nombre', 'jaula__codigo'],
                'unique_together': {('especie', 'cepa', 'jaula')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO_NACIMIENTO', 'Ingreso por nacimiento'), ('INGRESO_COMPRA', 'Ingreso por compra'), ('SALIDA_VENTA', 'Salida por venta'), ('SALIDA_PROTOCOLO', 'Salida a protocolo'), ('SALIDA_EUTANASIA', 'Salida por eutanasia'), ('SALIDA_MUERTE', 'Salida por muerte'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('TRASLADO', 'Traslado entre jaulas')], max_length=20)),
                ('cantidad_machos', models.PositiveIntegerField(default=0)),
                ('cantidad_hembras', models.PositiveIntegerField(default=0)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='animales.grupoanimal')),
                ('grupo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibidos', to='animales.grupoanimal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
