# Generated by Django 5.2.5 on 2025-09-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoanimal',
            options={'ordering': ['especie__nombre', 'cepa__nombre', 'jaula__nombre']},
        ),
        migrations.AlterModelOptions(
            name='jaula',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='jaula',
            old_name='codigo',
            new_name='nombre',
        ),
    ]
