# Generated by Django 5.2.7 on 2025-10-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004__categoriaTraslado'),
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientogrupo',
            name='categoria',
            field=models.CharField(choices=[('ING', 'Ingreso'), ('SAL', 'Salida'), ('AJU', 'Ajuste'), ('TRA', 'Traslado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movimientogrupo',
            name='motivo',
            field=models.CharField(choices=[('NAC', 'Nacimiento'), ('COM', 'Compra'), ('VEN', 'Venta'), ('EUT', 'Eutanasia'), ('MUE', 'Muerte'), ('PRO', 'Protocolo'), ('APO', 'Ajuste positivo'), ('ANE', 'Ajuste negativo'), ('TRA', 'Traslado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movimientogrupo',
            name='protocolo',
            field=models.ForeignKey(blank=True, help_text="Requerido si el motivo es 'Protocolo'.", limit_choices_to={'estado': 'aprobado'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='protocolos.protocolo'),
        ),
    ]
