# Generated by Django 5.2.6 on 2025-10-04 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado a CICUAL'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('instituciones', models.TextField(blank=True)),
                ('inv_nombre', models.CharField(max_length=200, verbose_name='Investigador responsable')),
                ('inv_departamento', models.CharField(blank=True, max_length=200)),
                ('inv_telefono', models.CharField(blank=True, max_length=100)),
                ('inv_email', models.EmailField(blank=True, max_length=254)),
                ('justificacion', models.TextField()),
                ('justificacion_3r', models.TextField()),
                ('transporte', models.TextField(blank=True)),
                ('tiempo_permanencia', models.CharField(blank=True, max_length=200)),
                ('descripcion_procedimientos', models.TextField(blank=True)),
                ('parametros_anestesia', models.TextField(blank=True)),
                ('cuidados_pre_post', models.TextField(blank=True)),
                ('punto_final_humano', models.TextField(blank=True)),
                ('metodo_eutanasia', models.TextField(blank=True)),
                ('riesgo_biologico', models.BooleanField(default=False)),
                ('nivel_absl', models.CharField(blank=True, max_length=50, verbose_name='Nivel de Bioseguridad (ABSL)')),
                ('destino_animales', models.TextField(blank=True)),
                ('n_grupos', models.PositiveIntegerField(default=0)),
                ('n_por_grupo', models.PositiveIntegerField(default=0)),
                ('n_total', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('aplica', models.BooleanField(default=False)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
            },
        ),
        migrations.CreateModel(
            name='Analgesico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('agente', models.CharField(max_length=150)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('via', models.CharField(blank=True, max_length=100, verbose_name='Vía de administración')),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analgesicos', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocoloAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('rango_peso', models.CharField(blank=True, max_length=100)),
                ('rango_edad', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('ND', 'No definido')], default='ND', max_length=2)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='protocolos.protocolo')),
            ],
        ),
    ]
