# Generated by Django 5.2.7 on 2025-10-26 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='ProtocoloInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('adscripcion', models.CharField(blank=True, help_text='Unidad/Departamento/Institución', max_length=200)),
                ('rol', models.CharField(blank=True, help_text='Ej.: Responsable, Coinvestigador, Tesista, Técnico', max_length=120)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tiene_ayudantes', models.BooleanField(default=False, help_text='Marcar si este investigador tendrá ayudantes')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigadores', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Investigador participante',
                'verbose_name_plural': 'Investigadores participantes',
            },
        ),
    ]
