# Generated by Django 5.2.7 on 2025-10-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0002_alter_protocolo_estado_protocoloinvestigador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoloinvestigador',
            name='tiene_ayudantes',
        ),
    ]
