# Generated by Django 5.2.8 on 2025-11-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_remove_protocoloinvestigador_tiene_ayudantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Procedimiento base',
                'verbose_name_plural': 'Procedimientos base',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='protocolos.procedimientobase'),
        ),
    ]
