# Generated by Django 5.2.8 on 2025-11-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0006_procedimientos_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='declaracion_buena_practica',
            field=models.BooleanField(default=False, verbose_name='Acepto la declaración de buenas prácticas'),
        ),
    ]
