# Generated by Django 5.2.8 on 2025-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0007_protocolo_declaracion_buena_practica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='protocolo',
            name='observacion_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analgesico',
            name='agente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='instituciones',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='instituciones',
            field=models.ManyToManyField(blank=True, related_name='protocolos', to='protocolos.institucion', verbose_name='Instituciones donde se realizará el proyecto'),
        ),
    ]
