# Generated by Django 5.2.8 on 2025-11-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0008_institucion_protocolo_observacion_rechazo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='activa',
            new_name='activo',
        ),
    ]
