# Generated by Django 5.2.9 on 2025-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0009_rename_activa_institucion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
